# coding: utf-8

# flake8: noqa

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

__version__ = "1.25.0"

# import ApiClient
from deel_python_sdk.api_client import ApiClient

# import Configuration
from deel_python_sdk.configuration import Configuration

# import exceptions
from deel_python_sdk.exceptions import OpenApiException
from deel_python_sdk.exceptions import ApiAttributeError
from deel_python_sdk.exceptions import ApiTypeError
from deel_python_sdk.exceptions import ApiValueError
from deel_python_sdk.exceptions import ApiKeyError
from deel_python_sdk.exceptions import ApiException

from deel_python_sdk.client import Deel
