# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

import unittest

import deel_python_sdk
from deel_python_sdk.model.basic_invoice_adjustment_contract import BasicInvoiceAdjustmentContract
from deel_python_sdk import configuration


class TestBasicInvoiceAdjustmentContract(unittest.TestCase):
    """BasicInvoiceAdjustmentContract unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
