# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from deel_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from deel_python_sdk.api_response import AsyncGeneratorResponse
from deel_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from deel_python_sdk import schemas  # noqa: F401

from deel_python_sdk.model.timesheet_list_container import TimesheetListContainer as TimesheetListContainerSchema
from deel_python_sdk.model.api_error_container import ApiErrorContainer as ApiErrorContainerSchema
from deel_python_sdk.model.timesheet_status_enum_list import TimesheetStatusEnumList as TimesheetStatusEnumListSchema
from deel_python_sdk.model.date_string import DateString as DateStringSchema
from deel_python_sdk.model.contract_type_enum_list import ContractTypeEnumList as ContractTypeEnumListSchema

from deel_python_sdk.type.api_error_container import ApiErrorContainer
from deel_python_sdk.type.timesheet_list_container import TimesheetListContainer
from deel_python_sdk.type.contract_type_enum_list import ContractTypeEnumList
from deel_python_sdk.type.timesheet_status_enum_list import TimesheetStatusEnumList
from deel_python_sdk.type.date_string import DateString

from ...api_client import Dictionary
from deel_python_sdk.pydantic.timesheet_status_enum_list import TimesheetStatusEnumList as TimesheetStatusEnumListPydantic
from deel_python_sdk.pydantic.contract_type_enum_list import ContractTypeEnumList as ContractTypeEnumListPydantic
from deel_python_sdk.pydantic.timesheet_list_container import TimesheetListContainer as TimesheetListContainerPydantic
from deel_python_sdk.pydantic.date_string import DateString as DateStringPydantic
from deel_python_sdk.pydantic.api_error_container import ApiErrorContainer as ApiErrorContainerPydantic

from . import path

# Query params
ContractTypesSchema = ContractTypeEnumListSchema
StatusesSchema = TimesheetStatusEnumListSchema
ReporterIdSchema = schemas.NumberSchema


class DateFromSchema(
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneMixin
):


    def __new__(
        cls,
        *args: typing.Union[None, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DateFromSchema':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class DateToSchema(
    schemas.NoneBase,
    schemas.Schema,
    schemas.NoneMixin
):


    def __new__(
        cls,
        *args: typing.Union[None, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'DateToSchema':
        return super().__new__(
            cls,
            *args,
            _configuration=_configuration,
        )


class LimitSchema(
    schemas.NumberSchema
):


    class MetaOapg:
        format = 'int64'
        inclusive_maximum = 99
        inclusive_minimum = 1


class OffsetSchema(
    schemas.NumberSchema
):


    class MetaOapg:
        format = 'int64'
        inclusive_maximum = 999999999
        inclusive_minimum = 0
RequestRequiredQueryParams = typing_extensions.TypedDict(
    'RequestRequiredQueryParams',
    {
    }
)
RequestOptionalQueryParams = typing_extensions.TypedDict(
    'RequestOptionalQueryParams',
    {
        'contract_types': typing.Union[ContractTypesSchema, ],
        'statuses': typing.Union[StatusesSchema, ],
        'reporter_id': typing.Union[ReporterIdSchema, decimal.Decimal, int, float, ],
        'date_from': typing.Union[DateFromSchema, None, ],
        'date_to': typing.Union[DateToSchema, None, ],
        'limit': typing.Union[LimitSchema, decimal.Decimal, int, float, ],
        'offset': typing.Union[OffsetSchema, decimal.Decimal, int, float, ],
    },
    total=False
)


class RequestQueryParams(RequestRequiredQueryParams, RequestOptionalQueryParams):
    pass


request_query_contract_types = api_client.QueryParameter(
    name="contract_types",
    style=api_client.ParameterStyle.FORM,
    schema=ContractTypeEnumListSchema,
    explode=True,
)
request_query_statuses = api_client.QueryParameter(
    name="statuses",
    style=api_client.ParameterStyle.FORM,
    schema=TimesheetStatusEnumListSchema,
    explode=True,
)
request_query_reporter_id = api_client.QueryParameter(
    name="reporter_id",
    style=api_client.ParameterStyle.FORM,
    schema=ReporterIdSchema,
    explode=True,
)
request_query_date_from = api_client.QueryParameter(
    name="date_from",
    style=api_client.ParameterStyle.FORM,
    schema=DateStringSchema,
    explode=True,
)
request_query_date_to = api_client.QueryParameter(
    name="date_to",
    style=api_client.ParameterStyle.FORM,
    schema=DateStringSchema,
    explode=True,
)
request_query_limit = api_client.QueryParameter(
    name="limit",
    style=api_client.ParameterStyle.FORM,
    schema=LimitSchema,
    explode=True,
)
request_query_offset = api_client.QueryParameter(
    name="offset",
    style=api_client.ParameterStyle.FORM,
    schema=OffsetSchema,
    explode=True,
)
# Path params
ContractIdSchema = schemas.StrSchema
RequestRequiredPathParams = typing_extensions.TypedDict(
    'RequestRequiredPathParams',
    {
        'contract_id': typing.Union[ContractIdSchema, str, ],
    }
)
RequestOptionalPathParams = typing_extensions.TypedDict(
    'RequestOptionalPathParams',
    {
    },
    total=False
)


class RequestPathParams(RequestRequiredPathParams, RequestOptionalPathParams):
    pass


request_path_contract_id = api_client.PathParameter(
    name="contract_id",
    style=api_client.ParameterStyle.SIMPLE,
    schema=ContractIdSchema,
    required=True,
)
_auth = [
    'deelToken',
    'oauth2',
]
SchemaFor200ResponseBodyApplicationJson = TimesheetListContainerSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: TimesheetListContainer


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: TimesheetListContainer


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
    },
)
SchemaFor400ResponseBodyApplicationJson = ApiErrorContainerSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ApiErrorContainer


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ApiErrorContainer


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
    },
)
SchemaFor401ResponseBodyApplicationJson = ApiErrorContainerSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: ApiErrorContainer


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: ApiErrorContainer


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
    },
)
SchemaFor403ResponseBodyApplicationJson = ApiErrorContainerSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: ApiErrorContainer


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: ApiErrorContainer


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
    },
)
SchemaFor404ResponseBodyApplicationJson = ApiErrorContainerSchema


@dataclass
class ApiResponseFor404(api_client.ApiResponse):
    body: ApiErrorContainer


@dataclass
class ApiResponseFor404Async(api_client.AsyncApiResponse):
    body: ApiErrorContainer


_response_for_404 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor404,
    response_cls_async=ApiResponseFor404Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor404ResponseBodyApplicationJson),
    },
)
SchemaFor405ResponseBodyApplicationJson = ApiErrorContainerSchema


@dataclass
class ApiResponseFor405(api_client.ApiResponse):
    body: ApiErrorContainer


@dataclass
class ApiResponseFor405Async(api_client.AsyncApiResponse):
    body: ApiErrorContainer


_response_for_405 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor405,
    response_cls_async=ApiResponseFor405Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor405ResponseBodyApplicationJson),
    },
)
SchemaFor429ResponseBodyApplicationJson = ApiErrorContainerSchema


@dataclass
class ApiResponseFor429(api_client.ApiResponse):
    body: ApiErrorContainer


@dataclass
class ApiResponseFor429Async(api_client.AsyncApiResponse):
    body: ApiErrorContainer


_response_for_429 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor429,
    response_cls_async=ApiResponseFor429Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor429ResponseBodyApplicationJson),
    },
)
SchemaFor500ResponseBodyApplicationJson = ApiErrorContainerSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: ApiErrorContainer


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: ApiErrorContainer


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '401': _response_for_401,
    '403': _response_for_403,
    '404': _response_for_404,
    '405': _response_for_405,
    '429': _response_for_429,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
)


class BaseApi(api_client.Api):

    def _list_by_contract_mapped_args(
        self,
        contract_id: str,
        contract_types: typing.Optional[ContractTypeEnumList] = None,
        statuses: typing.Optional[TimesheetStatusEnumList] = None,
        reporter_id: typing.Optional[typing.Union[int, float]] = None,
        date_from: typing.Optional[DateString] = None,
        date_to: typing.Optional[DateString] = None,
        limit: typing.Optional[typing.Union[int, float]] = None,
        offset: typing.Optional[typing.Union[int, float]] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _query_params = {}
        _path_params = {}
        if contract_types is not None:
            _query_params["contract_types"] = contract_types
        if statuses is not None:
            _query_params["statuses"] = statuses
        if reporter_id is not None:
            _query_params["reporter_id"] = reporter_id
        if date_from is not None:
            _query_params["date_from"] = date_from
        if date_to is not None:
            _query_params["date_to"] = date_to
        if limit is not None:
            _query_params["limit"] = limit
        if offset is not None:
            _query_params["offset"] = offset
        if contract_id is not None:
            _path_params["contract_id"] = contract_id
        args.query = _query_params
        args.path = _path_params
        return args

    async def _alist_by_contract_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        List of timesheets by contract
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_contract_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_contract_types,
            request_query_statuses,
            request_query_reporter_id,
            request_query_date_from,
            request_query_date_to,
            request_query_limit,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/contracts/{contract_id}/timesheets',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _list_by_contract_oapg(
        self,
            query_params: typing.Optional[dict] = {},
            path_params: typing.Optional[dict] = {},
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        List of timesheets by contract
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        self._verify_typed_dict_inputs_oapg(RequestQueryParams, query_params)
        self._verify_typed_dict_inputs_oapg(RequestPathParams, path_params)
        used_path = path.value
    
        _path_params = {}
        for parameter in (
            request_path_contract_id,
        ):
            parameter_data = path_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            serialized_data = parameter.serialize(parameter_data)
            _path_params.update(serialized_data)
    
        for k, v in _path_params.items():
            used_path = used_path.replace('{%s}' % k, v)
    
        prefix_separator_iterator = None
        for parameter in (
            request_query_contract_types,
            request_query_statuses,
            request_query_reporter_id,
            request_query_date_from,
            request_query_date_to,
            request_query_limit,
            request_query_offset,
        ):
            parameter_data = query_params.get(parameter.name, schemas.unset)
            if parameter_data is schemas.unset:
                continue
            if prefix_separator_iterator is None:
                prefix_separator_iterator = parameter.get_prefix_separator_iterator()
            serialized_data = parameter.serialize(parameter_data, prefix_separator_iterator)
            for serialized_value in serialized_data.values():
                used_path += serialized_value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'get'.upper()
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/contracts/{contract_id}/timesheets',
            auth_settings=_auth,
            headers=_headers,
        )
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            auth_settings=_auth,
            prefix_separator_iterator=prefix_separator_iterator,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class ListByContractRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def alist_by_contract(
        self,
        contract_id: str,
        contract_types: typing.Optional[ContractTypeEnumList] = None,
        statuses: typing.Optional[TimesheetStatusEnumList] = None,
        reporter_id: typing.Optional[typing.Union[int, float]] = None,
        date_from: typing.Optional[DateString] = None,
        date_to: typing.Optional[DateString] = None,
        limit: typing.Optional[typing.Union[int, float]] = None,
        offset: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_by_contract_mapped_args(
            contract_id=contract_id,
            contract_types=contract_types,
            statuses=statuses,
            reporter_id=reporter_id,
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            offset=offset,
        )
        return await self._alist_by_contract_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def list_by_contract(
        self,
        contract_id: str,
        contract_types: typing.Optional[ContractTypeEnumList] = None,
        statuses: typing.Optional[TimesheetStatusEnumList] = None,
        reporter_id: typing.Optional[typing.Union[int, float]] = None,
        date_from: typing.Optional[DateString] = None,
        date_to: typing.Optional[DateString] = None,
        limit: typing.Optional[typing.Union[int, float]] = None,
        offset: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_by_contract_mapped_args(
            contract_id=contract_id,
            contract_types=contract_types,
            statuses=statuses,
            reporter_id=reporter_id,
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            offset=offset,
        )
        return self._list_by_contract_oapg(
            query_params=args.query,
            path_params=args.path,
        )

class ListByContract(BaseApi):

    async def alist_by_contract(
        self,
        contract_id: str,
        contract_types: typing.Optional[ContractTypeEnumList] = None,
        statuses: typing.Optional[TimesheetStatusEnumList] = None,
        reporter_id: typing.Optional[typing.Union[int, float]] = None,
        date_from: typing.Optional[DateString] = None,
        date_to: typing.Optional[DateString] = None,
        limit: typing.Optional[typing.Union[int, float]] = None,
        offset: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
        **kwargs,
    ) -> TimesheetListContainerPydantic:
        raw_response = await self.raw.alist_by_contract(
            contract_id=contract_id,
            contract_types=contract_types,
            statuses=statuses,
            reporter_id=reporter_id,
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            offset=offset,
            **kwargs,
        )
        if validate:
            return TimesheetListContainerPydantic(**raw_response.body)
        return api_client.construct_model_instance(TimesheetListContainerPydantic, raw_response.body)
    
    
    def list_by_contract(
        self,
        contract_id: str,
        contract_types: typing.Optional[ContractTypeEnumList] = None,
        statuses: typing.Optional[TimesheetStatusEnumList] = None,
        reporter_id: typing.Optional[typing.Union[int, float]] = None,
        date_from: typing.Optional[DateString] = None,
        date_to: typing.Optional[DateString] = None,
        limit: typing.Optional[typing.Union[int, float]] = None,
        offset: typing.Optional[typing.Union[int, float]] = None,
        validate: bool = False,
    ) -> TimesheetListContainerPydantic:
        raw_response = self.raw.list_by_contract(
            contract_id=contract_id,
            contract_types=contract_types,
            statuses=statuses,
            reporter_id=reporter_id,
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            offset=offset,
        )
        if validate:
            return TimesheetListContainerPydantic(**raw_response.body)
        return api_client.construct_model_instance(TimesheetListContainerPydantic, raw_response.body)


class ApiForget(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def aget(
        self,
        contract_id: str,
        contract_types: typing.Optional[ContractTypeEnumList] = None,
        statuses: typing.Optional[TimesheetStatusEnumList] = None,
        reporter_id: typing.Optional[typing.Union[int, float]] = None,
        date_from: typing.Optional[DateString] = None,
        date_to: typing.Optional[DateString] = None,
        limit: typing.Optional[typing.Union[int, float]] = None,
        offset: typing.Optional[typing.Union[int, float]] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._list_by_contract_mapped_args(
            contract_id=contract_id,
            contract_types=contract_types,
            statuses=statuses,
            reporter_id=reporter_id,
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            offset=offset,
        )
        return await self._alist_by_contract_oapg(
            query_params=args.query,
            path_params=args.path,
            **kwargs,
        )
    
    def get(
        self,
        contract_id: str,
        contract_types: typing.Optional[ContractTypeEnumList] = None,
        statuses: typing.Optional[TimesheetStatusEnumList] = None,
        reporter_id: typing.Optional[typing.Union[int, float]] = None,
        date_from: typing.Optional[DateString] = None,
        date_to: typing.Optional[DateString] = None,
        limit: typing.Optional[typing.Union[int, float]] = None,
        offset: typing.Optional[typing.Union[int, float]] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._list_by_contract_mapped_args(
            contract_id=contract_id,
            contract_types=contract_types,
            statuses=statuses,
            reporter_id=reporter_id,
            date_from=date_from,
            date_to=date_to,
            limit=limit,
            offset=offset,
        )
        return self._list_by_contract_oapg(
            query_params=args.query,
            path_params=args.path,
        )

