# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.country_code import CountryCode

class Address(BaseModel):
    # Street and number.
    street_address: typing.Optional[str] = Field(None, alias='streetAddress')

    # Locality name.
    locality: typing.Optional[str] = Field(None, alias='locality')

    # Region code.
    region: typing.Optional[str] = Field(None, alias='region')

    # Postal code.
    postal_code: typing.Optional[str] = Field(None, alias='postalCode')

    country: typing.Optional[CountryCode] = Field(None, alias='country')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
