# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.client_legal_entity import ClientLegalEntity
from deel_python_sdk.pydantic.email_type import EmailType
from deel_python_sdk.pydantic.team_of_contract import TeamOfContract

class ClientOfContract(BaseModel):
    team: TeamOfContract = Field(alias='team')

    legal_entity: ClientLegalEntity = Field(alias='legal_entity')

    # Unique identifier of this resource.
    id: typing.Optional[str] = Field(None, alias='id')

    full_name: typing.Optional[str] = Field(None, alias='full_name')

    email: typing.Optional[EmailType] = Field(None, alias='email')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
