# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.employment_detail_contract_coverage import EmploymentDetailContractCoverage
from deel_python_sdk.pydantic.employment_detail_team import EmploymentDetailTeam
from deel_python_sdk.pydantic.people_client_legal_entity import PeopleClientLegalEntity
from deel_python_sdk.pydantic.people_payment import PeoplePayment

class EmploymentDetail(BaseModel):
    # Unique identifier for the employment.
    id: typing.Optional[str] = Field(None, alias='id')

    # Name of the employee.
    name: typing.Optional[str] = Field(None, alias='name')

    team: typing.Optional[EmploymentDetailTeam] = Field(None, alias='team')

    # The work email of the employee.
    email: typing.Optional[str] = Field(None, alias='email')

    # The state of employment.
    state: typing.Optional[str] = Field(None, alias='state')

    # The country of employment.
    country: typing.Optional[str] = Field(None, alias='country')

    payment: typing.Optional[PeoplePayment] = Field(None, alias='payment')

    # Whether the employment has ended.
    is_ended: typing.Optional[bool] = Field(None, alias='is_ended')

    # The timezone of the employment.
    timezone: typing.Optional[str] = Field(None, alias='timezone')

    # The job title of the employment.
    job_title: typing.Optional[str] = Field(None, alias='job_title')

    # The seniority level of the employment.
    seniority: typing.Optional[str] = Field(None, alias='seniority')

    # The start date of the employment.
    start_date: typing.Optional[date] = Field(None, alias='start_date')

    # The work email of the employment.
    work_email: typing.Optional[str] = Field(None, alias='work_email')

    # The type of hiring of the employment.
    hiring_type: typing.Optional[str] = Field(None, alias='hiring_type')

    # The current hiring status of the employment.
    hiring_status: typing.Optional[str] = Field(None, alias='hiring_status')

    # The completion date of the employment contract.
    completion_date: typing.Optional[str] = Field(None, alias='completion_date')

    # The status of the employment contract.
    contract_status: typing.Optional[str] = Field(None, alias='contract_status')

    # Whether the employee voluntarily left the employment.
    voluntarily_left: typing.Optional[str] = Field(None, alias='voluntarily_left')

    contract_coverage: typing.Optional[EmploymentDetailContractCoverage] = Field(None, alias='contract_coverage')

    # The new hiring status of the employment.
    new_hiring_status: typing.Optional[str] = Field(None, alias='new_hiring_status')

    client_legal_entity: typing.Optional[PeopleClientLegalEntity] = Field(None, alias='client_legal_entity')

    # Whether the employment has an EOR termination.
    has_eor_termination: typing.Optional[str] = Field(None, alias='has_eor_termination')

    # Whether the employment contract is archived.
    contract_is_archived: typing.Optional[bool] = Field(None, alias='contract_is_archived')

    # Whether the contract has a contractor.
    contract_has_contractor: typing.Optional[bool] = Field(None, alias='contract_has_contractor')

    # Whether the user contract is deleted.
    is_user_contract_deleted: typing.Optional[bool] = Field(None, alias='is_user_contract_deleted')

    # The HRIS direct employee invitation status.
    hris_direct_employee_invitation: typing.Optional[str] = Field(None, alias='hris_direct_employee_invitation')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
