# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.eor_contract_to_create_client import EorContractToCreateClient
from deel_python_sdk.pydantic.eor_contract_to_create_compensation_details import EorContractToCreateCompensationDetails
from deel_python_sdk.pydantic.eor_contract_to_create_employee import EorContractToCreateEmployee
from deel_python_sdk.pydantic.eor_contract_to_create_employment import EorContractToCreateEmployment
from deel_python_sdk.pydantic.eor_contract_to_create_quote_additional_fields import EorContractToCreateQuoteAdditionalFields
from deel_python_sdk.pydantic.eor_contract_to_create_seniority import EorContractToCreateSeniority
from deel_python_sdk.pydantic.pension_eor_contract_to_create import PensionEORContractToCreate

class EorContractToCreate(BaseModel):
    employee: EorContractToCreateEmployee = Field(alias='employee')

    employment: EorContractToCreateEmployment = Field(alias='employment')

    # Employee's job title.
    job_title: str = Field(alias='job_title')

    seniority: EorContractToCreateSeniority = Field(alias='seniority')

    client: EorContractToCreateClient = Field(alias='client')

    compensation_details: EorContractToCreateCompensationDetails = Field(alias='compensation_details')

    quote_additional_fields: typing.Optional[EorContractToCreateQuoteAdditionalFields] = Field(None, alias='quote_additional_fields')

    # Healthcare plan id. You can see available healthcare plans in the country guide endpoint.
    health_plan_id: typing.Optional[str] = Field(None, alias='health_plan_id')

    pension: typing.Optional[PensionEORContractToCreate] = Field(None, alias='pension')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
