# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class EorContractCreatedCompensationDetails(BaseModel):
    # Gross annual salary.
    salary: typing.Optional[typing.Union[int, float]] = Field(None, alias='salary')

    # Currency of gross annual salary.
    currency: typing.Optional[str] = Field(None, alias='currency')

    # Variable compensation acount or percentage.
    variable_compensation: typing.Optional[str] = Field(None, alias='variable_compensation')

    # Type fo variable compensation.
    variable_compensation_type: typing.Optional[typing.Optional[str]] = Field(None, alias='variable_compensation_type')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
