# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.contract_type_enum_for_estimate import ContractTypeEnumForEstimate
from deel_python_sdk.pydantic.country_code import CountryCode
from deel_python_sdk.pydantic.date_string_required import DateStringRequired
from deel_python_sdk.pydantic.estimate_first_payment_compensation_details import EstimateFirstPaymentCompensationDetails

class EstimateFirstPayment(BaseModel):
    type: ContractTypeEnumForEstimate = Field(alias='type')

    country_code: CountryCode = Field(alias='country_code')

    start_date: DateStringRequired = Field(alias='start_date')

    compensation_details: EstimateFirstPaymentCompensationDetails = Field(alias='compensation_details')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
