# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.get_employee_compliance_documents_container_data_documents_item_filenames import GetEmployeeComplianceDocumentsContainerDataDocumentsItemFilenames

class GetEmployeeComplianceDocumentsContainerDataDocumentsItem(BaseModel):
    # A short description of the document.
    description: typing.Optional[str] = Field(None, alias='description')

    # Unique identifier of this resource.
    id: typing.Optional[str] = Field(None, alias='id')

    # The name of the document.
    name: typing.Optional[str] = Field(None, alias='name')

    # Denotes if this document has a template available for download
    has_template: typing.Optional[bool] = Field(None, alias='has_template')

    # Denotes if the document is available to fill out on Deel.
    fillable: typing.Optional[bool] = Field(None, alias='fillable')

    # Denotes if the document is optional or required.
    is_optional: typing.Optional[bool] = Field(None, alias='is_optional')

    # The country associated with this document.
    country: typing.Optional[str] = Field(None, alias='country')

    # The timestamp when this document was uploaded / supplied to Deel.
    uploaded_at: typing.Optional[str] = Field(None, alias='uploaded_at')

    filenames: typing.Optional[GetEmployeeComplianceDocumentsContainerDataDocumentsItemFilenames] = Field(None, alias='filenames')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
