# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.email_type_required import EmailTypeRequired
from deel_python_sdk.pydantic.gp_contract_to_create_employee_address import GPContractToCreateEmployeeAddress

class GPContractToCreateEmployee(BaseModel):
    # Employee's first name.
    first_name: str = Field(alias='first_name')

    # Employee's last name.
    last_name: str = Field(alias='last_name')

    email: EmailTypeRequired = Field(alias='email')

    work_email: EmailTypeRequired = Field(alias='work_email')

    address: GPContractToCreateEmployeeAddress = Field(alias='address')

    # Employee's nationality.
    nationality: typing.Optional[str] = Field(None, alias='nationality')

    # Employee's number.
    employee_number: typing.Optional[str] = Field(None, alias='employee_number')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
