# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class GPPayrollEventReportsItem(BaseModel):
    id: str = Field(alias='id')

    status: str = Field(alias='status')

    # Long date-time format following ISO-8601
    start_date: datetime = Field(alias='start_date')

    # Long date-time format following ISO-8601
    lock_date: datetime = Field(alias='lock_date')

    # Long date-time format following ISO-8601
    end_date: datetime = Field(alias='end_date')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
