# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class PeopleTimeOffContainer(BaseModel):
    # Time off type.
    type: typing.Optional[Literal["VACATION", "SICK_LEAVE", "OTHER"]] = Field(None, alias='type')

    # Start date of employee's time off.
    start_date: typing.Optional[str] = Field(None, alias='start_date')

    # End date of employee's time off.
    end_date: typing.Optional[str] = Field(None, alias='end_date')

    # Description for employee's time off.
    reason: typing.Optional[str] = Field(None, alias='reason')

    # Attachments for employee's time off.
    attachments: typing.Optional[typing.IO] = Field(None, alias='attachments')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
