# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.date_string_required import DateStringRequired

class TimesheetSharedProperties(BaseModel):
    description: str = Field(alias='description')

    # Id of a Deel contract.
    contract_id: str = Field(alias='contract_id')

    date_submitted: DateStringRequired = Field(alias='date_submitted')

    # This is based on the scale of work statement of the associated contract
    quantity: typing.Union[int, float] = Field(alias='quantity')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
