# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict


class UserMeta(BaseModel):
    # Latest version of resource.
    version: typing.Optional[str] = Field(None, alias='version')

    # Time at which the resource was created.
    created: typing.Optional[str] = Field(None, alias='created')

    # Time at which the resource was last modified.
    last_modified: typing.Optional[str] = Field(None, alias='lastModified')

    # Resource type.
    resource_type: typing.Optional[str] = Field(None, alias='resourceType')

    # API endpoint to retrieve resource.
    location: typing.Optional[str] = Field(None, alias='location')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
