# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel, ConfigDict

from deel_python_sdk.pydantic.webhook_item_events import WebhookItemEvents

class WebhookItem(BaseModel):
    # Webhook subscription description.
    description: typing.Optional[str] = Field(alias='description')

    # Unique identifier of this resource.
    id: str = Field(alias='id')

    # Webhook subscription name.
    name: typing.Optional[str] = Field(alias='name')

    # Status of webhook.
    status: Literal["enabled", "disabled"] = Field(alias='status')

    # Endpoint to receive webhook.
    url: str = Field(alias='url')

    # The webhook's signing key, used to generate webhook signatures.
    signing_key: typing.Optional[str] = Field(alias='signing_key')

    # Deel API version. Currently Deel accepts v1 or v2 version.
    api_version: str = Field(alias='api_version')

    events: WebhookItemEvents = Field(alias='events')

    # Time at which the webhook was created.
    created_at: str = Field(alias='created_at')

    # Time at which the webhook was updated.
    updated_at: str = Field(alias='updated_at')

    # Property to hide the webhook from frontend view. Commonly by Dell 3rd party apps
    hidden: typing.Optional[typing.Optional[bool]] = Field(None, alias='hidden')

    model_config = ConfigDict(
        protected_namespaces=(),
        arbitrary_types_allowed=True
    )
