# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from deel_python_sdk.type.candidate_status_enum import CandidateStatusEnum
from deel_python_sdk.type.country_code import CountryCode
from deel_python_sdk.type.date_string_required import DateStringRequired
from deel_python_sdk.type.email_type_required import EmailTypeRequired
from deel_python_sdk.type.nationality_type import NationalityType

class RequiredCandidateToPatch(TypedDict):
    status: CandidateStatusEnum

class OptionalCandidateToPatch(TypedDict, total=False):
    # Candidate's first name.
    first_name: str

    # Candidate's last name.
    last_name: str

    start_date: DateStringRequired

    # Job Title.
    job_title: str

    # Link to candidate's profile in ATS.
    link: str

    email: EmailTypeRequired

    nationality: NationalityType

    country: CountryCode

    # Job location state.
    state: str

class CandidateToPatch(RequiredCandidateToPatch, OptionalCandidateToPatch):
    pass
