# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCreatePeopleTimeoff(TypedDict):
    # Time off type.
    type: str

    # Start date of employee's time off.
    start_date: str

    # End date of employee's time off.
    end_date: str

    # Description for employee's time off.
    reason: str

class OptionalCreatePeopleTimeoff(TypedDict, total=False):
    # Attachments for employee's time off.
    attachments: typing.IO

class CreatePeopleTimeoff(RequiredCreatePeopleTimeoff, OptionalCreatePeopleTimeoff):
    pass
