# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from deel_python_sdk.type.employee_timeoffs_item_response_applied_changes import EmployeeTimeoffsItemResponseAppliedChanges
from deel_python_sdk.type.employee_timeoffs_item_response_attachments import EmployeeTimeoffsItemResponseAttachments
from deel_python_sdk.type.requester_time_off import RequesterTimeOff

class RequiredEmployeeTimeoffsItemResponse(TypedDict):
    pass

class OptionalEmployeeTimeoffsItemResponse(TypedDict, total=False):
    time_off_id: str

    time_off_type_id: str

    policy_id: str

    policy_name: str

    policy_type_name: str

    reason: str

    # Time off type.
    type: str

    requested_at: str

    reviewed_at: str

    with_multiple_dates: bool

    single_date: str

    created_at: str

    updated_at: str

    denial_reason: bool

    requester: RequesterTimeOff

    days_used_start_year: str

    days_used_end_year: str

    days_used: str

    start_date: str

    end_date: str

    is_start_date_half_day: bool

    is_end_date_half_day: bool

    attachments: EmployeeTimeoffsItemResponseAttachments

    change_request: str

    is_updated: bool

    applied_changes: EmployeeTimeoffsItemResponseAppliedChanges

    can_request_changes: bool

class EmployeeTimeoffsItemResponse(RequiredEmployeeTimeoffsItemResponse, OptionalEmployeeTimeoffsItemResponse):
    pass
