# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from deel_python_sdk.type.eor_contract_benefits_item_enrollment_details import EORContractBenefitsItemEnrollmentDetails
from deel_python_sdk.type.eor_contract_benefits_item_plan import EORContractBenefitsItemPlan
from deel_python_sdk.type.eor_contract_benefits_item_provider import EORContractBenefitsItemProvider

class RequiredEORContractBenefitsItem(TypedDict):
    pass

class OptionalEORContractBenefitsItem(TypedDict, total=False):
    # Unique identifier of the benefit.
    id: str

    # Name of the benefit.
    name: str

    provider: EORContractBenefitsItemProvider

    # Status of the offer.
    offer_status: str

    plan: EORContractBenefitsItemPlan

    enrollment_details: EORContractBenefitsItemEnrollmentDetails

class EORContractBenefitsItem(RequiredEORContractBenefitsItem, OptionalEORContractBenefitsItem):
    pass
