# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from deel_python_sdk.type.global_payroll_g2_n_report import GlobalPayrollG2NReport

class RequiredGlobalPayrollG2NReportContainer(TypedDict):
    data: typing.List[GlobalPayrollG2NReport]

class OptionalGlobalPayrollG2NReportContainer(TypedDict, total=False):
    pass

class GlobalPayrollG2NReportContainer(RequiredGlobalPayrollG2NReportContainer, OptionalGlobalPayrollG2NReportContainer):
    pass
