# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from deel_python_sdk.type.contract_status_enum import ContractStatusEnum
from deel_python_sdk.type.contract_type_enum import ContractTypeEnum
from deel_python_sdk.type.date_time_string import DateTimeString
from deel_python_sdk.type.gp_contract_created_client import GPContractCreatedClient
from deel_python_sdk.type.gp_contract_created_compensation_details import GPContractCreatedCompensationDetails
from deel_python_sdk.type.gp_contract_created_employee import GPContractCreatedEmployee
from deel_python_sdk.type.gp_contract_created_employment import GPContractCreatedEmployment

class RequiredGPContractCreated(TypedDict):
    pass

class OptionalGPContractCreated(TypedDict, total=False):
    # Id of the contract created.
    id: str

    type: ContractTypeEnum

    created_at: DateTimeString

    status: ContractStatusEnum

    # Employee's job title.
    job_title: str

    employment: GPContractCreatedEmployment

    client: GPContractCreatedClient

    compensation_details: GPContractCreatedCompensationDetails

    employee: GPContractCreatedEmployee

class GPContractCreated(RequiredGPContractCreated, OptionalGPContractCreated):
    pass
