# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredRequesterTimeOff(TypedDict):
    pass

class OptionalRequesterTimeOff(TypedDict, total=False):
    is_part_time: bool

    has_reached_end_date: bool

    # Unique identifier of this resource.
    id: str

    uuid: str

    hris_profile_id: str

    client_profile_id: str

    organization_id: typing.Union[int, float]

    country: str

    worker_type: str

    end_date: str

    part_time_percentage: str

    created_at: str

    updated_at: str

class RequesterTimeOff(RequiredRequesterTimeOff, OptionalRequesterTimeOff):
    pass
