# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from deel_python_sdk.paths.users.post import CreateUser
from deel_python_sdk.paths.users_id.delete import DeleteUser
from deel_python_sdk.paths.users_id.get import GetById
from deel_python_sdk.paths.users.get import ListDeelUsers
from deel_python_sdk.paths.users_id.patch import PartiallyUpdateUser
from deel_python_sdk.paths.users__search.post import SearchOrList
from deel_python_sdk.paths.users_id.put import UpdateUserById
from deel_python_sdk.apis.tags.user_api_raw import UserApiRaw


class UserApi(
    CreateUser,
    DeleteUser,
    GetById,
    ListDeelUsers,
    PartiallyUpdateUser,
    SearchOrList,
    UpdateUserById,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: UserApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = UserApiRaw(api_client)
