# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from deel_python_sdk import schemas  # noqa: F401


class ContractTypeEnum(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    Type of a contract
    """
    
    @schemas.classproperty
    def ONGOING_TIME_BASED(cls):
        return cls("ongoing_time_based")
    
    @schemas.classproperty
    def MILESTONES(cls):
        return cls("milestones")
    
    @schemas.classproperty
    def TIME_BASED(cls):
        return cls("time_based")
    
    @schemas.classproperty
    def PAY_AS_YOU_GO_TIME_BASED(cls):
        return cls("pay_as_you_go_time_based")
    
    @schemas.classproperty
    def COMMISSION(cls):
        return cls("commission")
    
    @schemas.classproperty
    def PAYG_MILESTONES(cls):
        return cls("payg_milestones")
    
    @schemas.classproperty
    def PAYG_TASKS(cls):
        return cls("payg_tasks")
    
    @schemas.classproperty
    def EOR(cls):
        return cls("eor")
    
    @schemas.classproperty
    def UNKNOWN(cls):
        return cls("unknown")
    
    @schemas.classproperty
    def EMPLOYEE(cls):
        return cls("employee")
    
    @schemas.classproperty
    def GLOBAL_PAYROLL(cls):
        return cls("global_payroll")
    
    @schemas.classproperty
    def SHIELD_MSA(cls):
        return cls("shield_msa")
    
    @schemas.classproperty
    def HRIS_DIRECT_EMPLOYEE(cls):
        return cls("hris_direct_employee")
