# coding: utf-8

"""
    Deel REST API

    API specification for Deel HR user provisioning API. This YAML file is a preview of the API Deel is building. We are looking forward to your feedback.

    The version of the OpenAPI document: 1.25.0
    Contact: apiteam@deel.com
    Generated by: https://konfigthis.com
"""

from dataclasses import dataclass
import typing_extensions
import urllib3
from pydantic import RootModel
from deel_python_sdk.request_before_hook import request_before_hook
import json
from urllib3._collections import HTTPHeaderDict

from deel_python_sdk.api_response import AsyncGeneratorResponse
from deel_python_sdk import api_client, exceptions
from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from deel_python_sdk import schemas  # noqa: F401

from deel_python_sdk.model.search_request_schemas import SearchRequestSchemas as SearchRequestSchemasSchema
from deel_python_sdk.model.error_response import ErrorResponse as ErrorResponseSchema
from deel_python_sdk.model.user_search_response import UserSearchResponse as UserSearchResponseSchema
from deel_python_sdk.model.search_request import SearchRequest as SearchRequestSchema

from deel_python_sdk.type.search_request_schemas import SearchRequestSchemas
from deel_python_sdk.type.search_request import SearchRequest
from deel_python_sdk.type.user_search_response import UserSearchResponse
from deel_python_sdk.type.error_response import ErrorResponse

from ...api_client import Dictionary
from deel_python_sdk.pydantic.user_search_response import UserSearchResponse as UserSearchResponsePydantic
from deel_python_sdk.pydantic.search_request_schemas import SearchRequestSchemas as SearchRequestSchemasPydantic
from deel_python_sdk.pydantic.search_request import SearchRequest as SearchRequestPydantic
from deel_python_sdk.pydantic.error_response import ErrorResponse as ErrorResponsePydantic

from . import path

# body param
SchemaForRequestBodyApplicationJson = SearchRequestSchema
SchemaForRequestBodyApplicationScimjson = SearchRequestSchema


request_body_body = api_client.RequestBody(
    content={
        'application/json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationJson),
        'application/scim+json': api_client.MediaType(
            schema=SchemaForRequestBodyApplicationScimjson),
    },
)
_auth = [
    'deelToken',
    'oauth2',
]
SchemaFor200ResponseBodyApplicationJson = UserSearchResponseSchema
SchemaFor200ResponseBodyApplicationScimjson = UserSearchResponseSchema


@dataclass
class ApiResponseFor200(api_client.ApiResponse):
    body: UserSearchResponse


@dataclass
class ApiResponseFor200Async(api_client.AsyncApiResponse):
    body: UserSearchResponse


_response_for_200 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor200,
    response_cls_async=ApiResponseFor200Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationJson),
        'application/scim+json': api_client.MediaType(
            schema=SchemaFor200ResponseBodyApplicationScimjson),
    },
)
SchemaFor400ResponseBodyApplicationJson = ErrorResponseSchema
SchemaFor400ResponseBodyApplicationScimjson = ErrorResponseSchema


@dataclass
class ApiResponseFor400(api_client.ApiResponse):
    body: ErrorResponse


@dataclass
class ApiResponseFor400Async(api_client.AsyncApiResponse):
    body: ErrorResponse


_response_for_400 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor400,
    response_cls_async=ApiResponseFor400Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationJson),
        'application/scim+json': api_client.MediaType(
            schema=SchemaFor400ResponseBodyApplicationScimjson),
    },
)
SchemaFor401ResponseBodyApplicationJson = ErrorResponseSchema
SchemaFor401ResponseBodyApplicationScimjson = ErrorResponseSchema


@dataclass
class ApiResponseFor401(api_client.ApiResponse):
    body: ErrorResponse


@dataclass
class ApiResponseFor401Async(api_client.AsyncApiResponse):
    body: ErrorResponse


_response_for_401 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor401,
    response_cls_async=ApiResponseFor401Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationJson),
        'application/scim+json': api_client.MediaType(
            schema=SchemaFor401ResponseBodyApplicationScimjson),
    },
)
SchemaFor403ResponseBodyApplicationJson = ErrorResponseSchema
SchemaFor403ResponseBodyApplicationScimjson = ErrorResponseSchema


@dataclass
class ApiResponseFor403(api_client.ApiResponse):
    body: ErrorResponse


@dataclass
class ApiResponseFor403Async(api_client.AsyncApiResponse):
    body: ErrorResponse


_response_for_403 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor403,
    response_cls_async=ApiResponseFor403Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationJson),
        'application/scim+json': api_client.MediaType(
            schema=SchemaFor403ResponseBodyApplicationScimjson),
    },
)
SchemaFor429ResponseBodyApplicationJson = ErrorResponseSchema
SchemaFor429ResponseBodyApplicationScimjson = ErrorResponseSchema


@dataclass
class ApiResponseFor429(api_client.ApiResponse):
    body: ErrorResponse


@dataclass
class ApiResponseFor429Async(api_client.AsyncApiResponse):
    body: ErrorResponse


_response_for_429 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor429,
    response_cls_async=ApiResponseFor429Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor429ResponseBodyApplicationJson),
        'application/scim+json': api_client.MediaType(
            schema=SchemaFor429ResponseBodyApplicationScimjson),
    },
)
SchemaFor500ResponseBodyApplicationJson = ErrorResponseSchema
SchemaFor500ResponseBodyApplicationScimjson = ErrorResponseSchema


@dataclass
class ApiResponseFor500(api_client.ApiResponse):
    body: ErrorResponse


@dataclass
class ApiResponseFor500Async(api_client.AsyncApiResponse):
    body: ErrorResponse


_response_for_500 = api_client.OpenApiResponse(
    response_cls=ApiResponseFor500,
    response_cls_async=ApiResponseFor500Async,
    content={
        'application/json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationJson),
        'application/scim+json': api_client.MediaType(
            schema=SchemaFor500ResponseBodyApplicationScimjson),
    },
)
_status_code_to_response = {
    '200': _response_for_200,
    '400': _response_for_400,
    '401': _response_for_401,
    '403': _response_for_403,
    '429': _response_for_429,
    '500': _response_for_500,
}
_all_accept_content_types = (
    'application/json',
    'application/scim+json',
)


class BaseApi(api_client.Api):

    def _search_or_list_mapped_args(
        self,
        count: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        schemas: typing.Optional[SearchRequestSchemas] = None,
        start_index: typing.Optional[int] = None,
    ) -> api_client.MappedArgs:
        args: api_client.MappedArgs = api_client.MappedArgs()
        _body = {}
        if count is not None:
            _body["count"] = count
        if filter is not None:
            _body["filter"] = filter
        if schemas is not None:
            _body["schemas"] = schemas
        if start_index is not None:
            _body["startIndex"] = start_index
        args.body = _body
        return args

    async def _asearch_or_list_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        """
        Search or list users
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/Users/.search',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_body.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = await self.api_client.async_call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
            **kwargs
        )
    
        if stream:
            if not 200 <= response.http_response.status <= 299:
                body = (await response.http_response.content.read()).decode("utf-8")
                raise exceptions.ApiStreamingException(
                    status=response.http_response.status,
                    reason=response.http_response.reason,
                    body=body,
                )
    
            async def stream_iterator():
                """
                iterates over response.http_response.content and closes connection once iteration has finished
                """
                async for line in response.http_response.content:
                    if line == b'\r\n':
                        continue
                    yield line
                response.http_response.close()
                await response.session.close()
            return AsyncGeneratorResponse(
                content=stream_iterator(),
                headers=response.http_response.headers,
                status=response.http_response.status,
                response=response.http_response
            )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = await response_for_status.deserialize_async(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserializationAsync(
                body=await response.http_response.json() if is_json else await response.http_response.text(),
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        # cleanup session / response
        response.http_response.close()
        await response.session.close()
    
        return api_response


    def _search_or_list_oapg(
        self,
        body: typing.Any = None,
        skip_deserialization: bool = True,
        timeout: typing.Optional[typing.Union[float, typing.Tuple]] = None,
        accept_content_types: typing.Tuple[str] = _all_accept_content_types,
        content_type: str = 'application/json',
        stream: bool = False,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        """
        Search or list users
        :param skip_deserialization: If true then api_response.response will be set but
            api_response.body and api_response.headers will not be deserialized into schema
            class instances
        """
        used_path = path.value
    
        _headers = HTTPHeaderDict()
        # TODO add cookie handling
        if accept_content_types:
            for accept_content_type in accept_content_types:
                _headers.add('Accept', accept_content_type)
        method = 'post'.upper()
        _headers.add('Content-Type', content_type)
    
        _fields = None
        _body = None
        request_before_hook(
            resource_path=used_path,
            method=method,
            configuration=self.api_client.configuration,
            path_template='/Users/.search',
            body=body,
            auth_settings=_auth,
            headers=_headers,
        )
        if body is not schemas.unset:
            serialized_data = request_body_body.serialize(body, content_type)
            if 'fields' in serialized_data:
                _fields = serialized_data['fields']
            elif 'body' in serialized_data:
                _body = serialized_data['body']
    
        response = self.api_client.call_api(
            resource_path=used_path,
            method=method,
            headers=_headers,
            fields=_fields,
            serialized_body=_body,
            body=body,
            auth_settings=_auth,
            timeout=timeout,
        )
    
        response_for_status = _status_code_to_response.get(str(response.http_response.status))
        if response_for_status:
            api_response = response_for_status.deserialize(
                                                    response,
                                                    self.api_client.configuration,
                                                    skip_deserialization=skip_deserialization
                                                )
        else:
            # If response data is JSON then deserialize for SDK consumer convenience
            is_json = api_client.JSONDetector._content_type_is_json(response.http_response.headers.get('Content-Type', ''))
            api_response = api_client.ApiResponseWithoutDeserialization(
                body=json.loads(response.http_response.data) if is_json else response.http_response.data,
                response=response.http_response,
                round_trip_time=response.round_trip_time,
                status=response.http_response.status,
                headers=response.http_response.headers,
            )
    
        if not 200 <= api_response.status <= 299:
            raise exceptions.ApiException(api_response=api_response)
    
        return api_response


class SearchOrListRaw(BaseApi):
    # this class is used by api classes that refer to endpoints with operationId fn names

    async def asearch_or_list(
        self,
        count: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        schemas: typing.Optional[SearchRequestSchemas] = None,
        start_index: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._search_or_list_mapped_args(
            count=count,
            filter=filter,
            schemas=schemas,
            start_index=start_index,
        )
        return await self._asearch_or_list_oapg(
            body=args.body,
            **kwargs,
        )
    
    def search_or_list(
        self,
        count: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        schemas: typing.Optional[SearchRequestSchemas] = None,
        start_index: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._search_or_list_mapped_args(
            count=count,
            filter=filter,
            schemas=schemas,
            start_index=start_index,
        )
        return self._search_or_list_oapg(
            body=args.body,
        )

class SearchOrList(BaseApi):

    async def asearch_or_list(
        self,
        count: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        schemas: typing.Optional[SearchRequestSchemas] = None,
        start_index: typing.Optional[int] = None,
        validate: bool = False,
        **kwargs,
    ) -> UserSearchResponsePydantic:
        raw_response = await self.raw.asearch_or_list(
            count=count,
            filter=filter,
            schemas=schemas,
            start_index=start_index,
            **kwargs,
        )
        if validate:
            return UserSearchResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(UserSearchResponsePydantic, raw_response.body)
    
    
    def search_or_list(
        self,
        count: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        schemas: typing.Optional[SearchRequestSchemas] = None,
        start_index: typing.Optional[int] = None,
        validate: bool = False,
    ) -> UserSearchResponsePydantic:
        raw_response = self.raw.search_or_list(
            count=count,
            filter=filter,
            schemas=schemas,
            start_index=start_index,
        )
        if validate:
            return UserSearchResponsePydantic(**raw_response.body)
        return api_client.construct_model_instance(UserSearchResponsePydantic, raw_response.body)


class ApiForpost(BaseApi):
    # this class is used by api classes that refer to endpoints by path and http method names

    async def apost(
        self,
        count: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        schemas: typing.Optional[SearchRequestSchemas] = None,
        start_index: typing.Optional[int] = None,
        **kwargs,
    ) -> typing.Union[
        ApiResponseFor200Async,
        api_client.ApiResponseWithoutDeserializationAsync,
        AsyncGeneratorResponse,
    ]:
        args = self._search_or_list_mapped_args(
            count=count,
            filter=filter,
            schemas=schemas,
            start_index=start_index,
        )
        return await self._asearch_or_list_oapg(
            body=args.body,
            **kwargs,
        )
    
    def post(
        self,
        count: typing.Optional[int] = None,
        filter: typing.Optional[str] = None,
        schemas: typing.Optional[SearchRequestSchemas] = None,
        start_index: typing.Optional[int] = None,
    ) -> typing.Union[
        ApiResponseFor200,
        api_client.ApiResponseWithoutDeserialization,
    ]:
        args = self._search_or_list_mapped_args(
            count=count,
            filter=filter,
            schemas=schemas,
            start_index=start_index,
        )
        return self._search_or_list_oapg(
            body=args.body,
        )

